const BOOKS={personal:'Cá nhân',shop:'Quán',company:'Doanh nghiệp'};
const CATS={personal:{income:['Lương','Forex','Trading','Phụ thu'],expense:['Sinh hoạt','Mua sắm','Quà cáp','Đi lại']},shop:{income:['Doanh thu','Thu khác'],expense:['Nguyên liệu','Lương nhân viên','Thuê mặt bằng','Điện nước','Marketing','Vận chuyển','Thiết bị','Khác']},company:{income:['Doanh thu','Thu công nợ','Thu khác'],expense:['Nhập hàng','Lương','Thuế','Kho vận','Văn phòng','Marketing','Công nợ','Khác']}};
const COLORS={'Lương':'#2563eb','Forex':'#7c3aed','Trading':'#0891b2','Phụ thu':'#06b6d4','Sinh hoạt':'#f59e0b','Mua sắm':'#ec4899','Quà cáp':'#f43f5e','Đi lại':'#16a34a','Doanh thu':'#2563eb','Thu khác':'#06b6d4','Nguyên liệu':'#f97316','Lương nhân viên':'#8b5cf6','Thuê mặt bằng':'#ef4444','Điện nước':'#eab308','Marketing':'#06b6d4','Vận chuyển':'#14b8a6','Thiết bị':'#64748b','Thu công nợ':'#16a34a','Nhập hàng':'#f97316','Lương':'#8b5cf6','Thuế':'#dc2626','Kho vận':'#0f766e','Văn phòng':'#6366f1','Công nợ':'#0891b2','Khác':'#94a3b8'};
const ICON={'Lương':'♙','Forex':'✣','Trading':'▟','Phụ thu':'＋','Sinh hoạt':'⌂','Mua sắm':'▣','Quà cáp':'♢','Đi lại':'▰'};
let book='personal',mode='income',selectedDate=new Date(),calDate=new Date(),filter='all';
let data=JSON.parse(localStorage.getItem('vtc_v9')||localStorage.getItem('vtc_v8')||localStorage.getItem('vtc_v7')||'[]');

if(!data.length){
 data=[
 {book:'personal',type:'income',amount:25000000,category:'Lương',date:'2026-09-14',note:'Thu nhập cá nhân'},
 {book:'personal',type:'expense',amount:2350000,category:'Mua sắm',date:'2026-09-13',note:'Chi tiêu cá nhân'},
 {book:'personal',type:'income',amount:12500000,category:'Forex',date:'2026-09-12',note:'Thu nhập cá nhân'},
 {book:'personal',type:'expense',amount:300000,category:'Đi lại',date:'2026-09-13',note:''},
 {book:'personal',type:'expense',amount:1200000,category:'Quà cáp',date:'2026-09-12',note:''}
 ];
}

const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,fmt=d=>`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`;
function rows(){return data.filter(x=>x.book===book)} function mr(){const k=iso(new Date()).slice(0,7);return rows().filter(x=>x.date.startsWith(k))}
function render(){const r=rows(),m=mr(),inc=m.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),out=m.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),bal=r.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0)-r.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);$('balance').textContent=money(bal);$('income').textContent=money(inc);$('expense').textContent=money(out);$('rIncome').textContent=money(inc);$('rExpense').textContent=money(out);$('donutVal').textContent=bal>=1e6?(bal/1e6).toFixed(1)+'M':money(bal);let recent=r.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('recent').innerHTML=recent.length?recent.map(item).join(''):'<div class="empty">Chưa có giao dịch</div>';let list=r.slice().sort((a,b)=>b.date.localeCompare(a.date));let q=($('search')?.value||'').toLowerCase();list=list.filter(x=>(filter==='all'||x.type===filter)&&(`${x.category} ${x.note||''}`.toLowerCase().includes(q)));$('allList').innerHTML=list.length?list.map(item).join(''):'<div class="empty">Không tìm thấy giao dịch</div>';cats();chart();localStorage.setItem('vtc_v9',JSON.stringify(data))}
function item(x){const c=COLORS[x.category]||'#64748b',sign=x.type==='income'?'+':'−',sym=ICON[x.category]||'⇄';return `<div class="item"><div class="ico" style="background:${c}18;color:${c}">${sym}</div><div class="info"><b>${x.category}</b><small>${x.date}${x.note?' · '+x.note:''}</small></div><div class="money ${x.type==='income'?'green':'red'}">${sign}${money(x.amount)}</div></div>`}
function cats(){const make=(arr)=>arr.map(c=>`<div class="catrow"><div class="ico" style="background:${COLORS[c]||'#94a3b8'}18;color:${COLORS[c]||'#94a3b8'}">${ICON[c]||'•'}</div><b>${c}</b><span>›</span></div>`).join('');$('incomeCats').innerHTML=make(CATS[book].income);$('expenseCats').innerHTML=make(CATS[book].expense)}
function chart(){const cv=$('chart');const r=cv.getBoundingClientRect(),d=devicePixelRatio||1;cv.width=r.width*d;cv.height=r.height*d;const x=cv.getContext('2d');x.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;x.clearRect(0,0,w,h);x.strokeStyle='#edf1f5';for(let i=1;i<5;i++){x.beginPath();x.moveTo(8,i*h/5);x.lineTo(w-8,i*h/5);x.stroke()}let m=mr(),max=Math.max(1,...m.map(v=>v.amount));[['income','#16a34a'],['expense','#e11d48']].forEach(([typ,col])=>{x.strokeStyle=col;x.lineWidth=3;x.beginPath();for(let i=0;i<12;i++){let total=m.filter(v=>v.type===typ).reduce((a,v)=>a+v.amount,0); let val=total*(0.15+((i*37)%85)/100),px=10+i*(w-20)/11,py=h-10-(val/max)*(h-25);i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()})}
function openForm(m){mode=m;$('modal').classList.remove('hidden');$('formTitle').textContent=m==='income'?'Thêm khoản thu':m==='expense'?'Thêm khoản chi':'Chuyển tiền';document.querySelectorAll('.seg button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('toWrap').classList.toggle('hidden',m!=='transfer');$('cat').disabled=m==='transfer';fillCats();selectedDate=new Date();$('pickedDate').textContent=fmt(selectedDate);$('amount').value='';$('note').value=''}
function fillCats(){$('cat').innerHTML=(mode==='transfer'?['Chuyển nội bộ']:CATS[book][mode]).map(x=>`<option>${x}</option>`).join('')}
function page(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));render()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>page(n.dataset.page));
document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{book=b.dataset.book;document.querySelectorAll('[data-book]').forEach(x=>x.classList.toggle('active',x.dataset.book===book));render()});
$('incomeBtn').onclick=()=>openForm('income');$('expenseBtn').onclick=()=>openForm('expense');$('transferBtn').onclick=()=>openForm('transfer');$('plus').onclick=()=>openForm('income');$('allBtn').onclick=()=>page('transactions');$('close').onclick=()=>$('modal').classList.add('hidden');
document.querySelectorAll('.seg button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.seg button').forEach(x=>x.classList.toggle('active',x===b));$('formTitle').textContent=mode==='income'?'Thêm khoản thu':mode==='expense'?'Thêm khoản chi':'Chuyển tiền';$('toWrap').classList.toggle('hidden',mode!=='transfer');$('cat').disabled=mode==='transfer';fillCats()});
$('save').onclick=()=>{let a=Number($('amount').value);if(!a)return alert('Nhập số tiền nhé');let date=iso(selectedDate),note=$('note').value.trim();if(mode==='transfer'){let to=$('toBook').value;if(to===book)return alert('Chọn sổ khác');data.push({book,type:'expense',amount:a,category:'Chuyển nội bộ',date,note});data.push({book:to,type:'income',amount:a,category:'Chuyển nội bộ',date,note})}else data.push({book,type:mode,amount:a,category:$('cat').value,date,note});$('modal').classList.add('hidden');render()};
$('search').oninput=render;document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()});
$('datePick').onclick=()=>page('calendar');$('start').onclick=()=>{$('splash').classList.add('hidden');$('app').classList.remove('hidden');render()};
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>page(b.dataset.back));
let now=new Date();function cal(){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate();$('calTitle').textContent=`Tháng ${m+1}, ${y}`;let h='';for(let i=0;i<42;i++){let n=i-start+1,d=n<1?new Date(y,m-1,new Date(y,m,0).getDate()+n):n>last?new Date(y,m+1,n-last):new Date(y,m,n);h+=`<button class="${d.getMonth()!==m?'muted ':''}${iso(d)===iso(selectedDate)?'sel':''}" data-d="${iso(d)}">${d.getDate()}</button>`}$('days').innerHTML=h;document.querySelectorAll('#days button').forEach(b=>b.onclick=()=>{let p=b.dataset.d.split('-').map(Number);selectedDate=new Date(p[0],p[1]-1,p[2]);cal();$('pickedDate').textContent=fmt(selectedDate);page('home')})}
$('prev').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);cal()};$('next').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);cal()};
$('monthBtn').onclick=()=>{calDate=new Date();page('calendar');cal()};fillCats();cal();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
