const names={personal:'Cá nhân',shop:'Quán',company:'Doanh nghiệp'};const cats={personal:{income:['Lương','Thu khác','Bán hàng'],expense:['Ăn uống','Sinh hoạt','Xăng xe','Mua sắm','Tiền nhà','Vay/mượn','Khác']},shop:{income:['Doanh thu','Thu khác'],expense:['Nguyên liệu','Lương nhân viên','Thuê mặt bằng','Điện nước','Marketing','Vận chuyển','Thiết bị','Khác']},company:{income:['Doanh thu','Thu công nợ','Thu khác'],expense:['Nhập hàng','Lương','Thuế','Kho vận','Văn phòng','Marketing','Công nợ','Khác']}};let book='personal',mode='expense';let data=JSON.parse(localStorage.getItem('vtc_v3')||'[]');const $=x=>document.getElementById(x);const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function setup(){let arr=[...cats[book].income,...cats[book].expense];$('category').innerHTML=arr.map(x=>`<option>${x}</option>`).join('');$('filter').innerHTML='<option value="all">Tất cả danh mục</option>'+arr.map(x=>`<option>${x}</option>`).join('');let now=new Date(),opts='';for(let i=0;i<12;i++){let d=new Date(now.getFullYear(),now.getMonth()-i,1),v=d.toISOString().slice(0,7);opts+=`<option value="${v}">${d.toLocaleDateString('vi-VN',{month:'long',year:'numeric'})}</option>`}$('month').innerHTML=opts}
function render(){let rows=data.filter(x=>x.book===book);let inc=rows.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),out=rows.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);$('bookName').textContent='• '+names[book];$('balance').textContent=money(inc-out);$('income').textContent=money(inc);$('expense').textContent=money(out);let mo=$('month').value, mr=rows.filter(x=>x.date.startsWith(mo));let mi=mr.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),me=mr.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);$('mincome').textContent=money(mi);$('mexpense').textContent=money(me);$('mprofit').textContent=money(mi-me);let total=mi+me;$('barIn').style.width=(total?mi/total*100:0)+'%';$('barOut').style.width=(total?me/total*100:0)+'%';let f=$('filter').value;rows=rows.filter(x=>f==='all'||x.category===f);$('list').innerHTML=rows.length?rows.slice().reverse().map(x=>`<div class="item"><div class="icon">${x.type==='income'?'💰':x.type==='expense'?'💸':'↔️'}</div><div class="info"><b>${esc(x.category)}</b><small>${esc(x.note||'')} · ${x.date}</small></div><div class="money ${x.type==='income'?'plus':'minus'}">${x.type==='income'?'+':'−'}${money(x.amount)}</div></div>`).join(''):'<div class="empty">Chưa có giao dịch trong sổ này.</div>';localStorage.setItem('vtc_v3',JSON.stringify(data))}
function open(m){mode=m;$('title').textContent=m==='income'?'Thêm khoản thu':m==='expense'?'Thêm khoản chi':'Chuyển tiền nội bộ';$('transferFields').classList.toggle('hidden',m!=='transfer');$('category').disabled=m==='transfer';if(m==='transfer')$('category').innerHTML='<option>Chuyển nội bộ</option>';else setup();$('date').value=new Date().toISOString().slice(0,10);$('amount').value='';$('note').value='';$('modal').classList.remove('hidden')}
document.querySelectorAll('#books button').forEach(b=>b.onclick=()=>{book=b.dataset.book;document.querySelectorAll('#books button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setup();render()});$('filter').onchange=render;$('month').onchange=render;$('addIn').onclick=()=>open('income');$('addOut').onclick=()=>open('expense');$('transfer').onclick=()=>open('transfer');$('close').onclick=()=>$('modal').classList.add('hidden');$('reset').onclick=()=>location.reload();
$('save').onclick=()=>{let amount=Number($('amount').value);if(!amount)return alert('Nhập số tiền nhé!');let note=$('note').value.trim(),date=$('date').value;if(mode==='transfer'){let to=$('toBook').value;if(to===book)return alert('Chọn sổ khác để chuyển!');data.push({book,type:'expense',amount,category:'Chuyển nội bộ → '+names[to],note,date});data.push({book:to,type:'income',amount,category:'Chuyển nội bộ ← '+names[book],note,date})}else data.push({book,type:mode,amount,category:$('category').value,note,date});$('modal').classList.add('hidden');render()};
function csv(bookFilter){let rows=data.filter(x=>!bookFilter||x.book===bookFilter);let lines=[['Sổ','Ngày','Loại','Danh mục','Số tiền','Ghi chú'].join(',')];rows.forEach(x=>lines.push([names[x.book],x.date,x.type==='income'?'Thu':'Chi',x.category,x.amount,(x.note||'').replaceAll('"','""')].map(v=>`"${v}"`).join(',')));return '\ufeff'+lines.join('\n')}
function download(text,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('exportBook').onclick=()=>download(csv(book),'Vu_Thu_Chi_'+book+'.csv');$('exportAll').onclick=()=>download(csv(),'Vu_Thu_Chi_tat_ca.csv');setup();render();